### ISSUE TITLE
Internal Server Error #18

### ISSUE THREAD

**Issue by banyous** [opentapioca/opentapioca#58]
Hi, 

Thanks for the nice project! I am encountering server error when attempting to use the OpenTapioca API, through this command : 

`curl 'https://opentapioca.org/api/annotate'  --data 'query=Associated+Press+writer+Julie+Pace+contributed+from+Washington.'`

Can you please check if the server is on?

Many thanks!

**Comment by wetneb** [comment]
Thanks for letting me know, I have restarted the server.

**Comment by banyous** [comment]
Hi, thanks a lot for your quick reply. But the error is still occuring. Here is the ouptut I'm getting : 
` <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;https://opentapioca.org/api/annotate&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>`

**Comment by wetneb** [comment]
Indeed, the machine it's running on is just too short on resources, so solr dies regularly.
